name: client_mobile
description: AREA mobile client

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
