name: client_mobile
description: AREA mobile client

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google.png
    - assets/icons/login.png

